security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring:
  application:
    name: userTesting
  datasource:
    url: jdbc:h2:file:~/coasterDB;FILE_LOCK=FS
    driverClassName: org.h2.Driver
    username: sa
    password: 